CREATE DATABASE Wildlife_tracker;

\c Wildlife-tracker;

CREATE TABLE animals(
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR,
                        type VARCHAR,
                        age VARCHAR,
                        health VARCHAR

);
CREATE TABLE sightings(
                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          animalName VARCHAR,
                          location VARCHAR,
                          rangerName VARCHAR,
                          Timestamp timestamp
);

CREATE DATABASE Wildlife-tracker WITH TEMPLATE Wildlife-tracker-test;