CREATE DATABASE wildlife_tracker;

\c wildlife_tracker;

CREATE TABLE animals(
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        animalname VARCHAR,
                        category VARCHAR,
                        age VARCHAR,
                        health VARCHAR

);
CREATE TABLE sightings(
                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          animalName VARCHAR,
                          location VARCHAR,
                          rangerName VARCHAR,
                          timeofsight timestamp
);

CREATE DATABASE wildlife_tracker_test WITH TEMPLATE wildlife_tracker;